name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to staging server
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF

            set -e

            cd ${{ secrets.DEPLOY_PATH }}

            LOCKFILE="/tmp/staging-deploy.lock"
            MAX_RETRIES=10
            RETRY_DELAY=60
            RETRIES=0

            echo "[INFO] Checking for existing deploy lock..."

            while [ -f "\$LOCKFILE" ]; do
              if [ \$RETRIES -ge \$MAX_RETRIES ]; then
                echo "[ERROR] Lockfile still exists after \$((MAX_RETRIES * RETRY_DELAY / 60)) minutes. Aborting."
                exit 1
              fi
              echo "[INFO] Another deploy is running. Waiting for \$RETRY_DELAY seconds..."
              sleep \$RETRY_DELAY
              RETRIES=\$((RETRIES + 1))
            done

            echo "[INFO] Acquiring deploy lock..."
            touch "\$LOCKFILE"

            trap 'echo "[INFO] Releasing deploy lock..."; rm -f "\$LOCKFILE"' EXIT

            echo "[INFO] Pulling latest code from master..."
            git pull origin master

            echo "[INFO] Stopping running containers..."
            docker compose -f docker-compose.staging.yml down

            echo "[INFO] Pruning unused Docker images..."
            docker image prune -f

            echo "[INFO] Rebuilding and restarting services..."
            docker-compose -f docker-compose.staging.yml up -d --build

            echo "[INFO] Deploy complete."

          EOF

